// Generated by CoffeeScript 1.4.0
(function() {

  jQuery(function($) {
    var caption, inp;
    caption = $('.main > .caption');
    inp = $('#report-date').DatePicker({
      format: 'b d, Y',
      mode: 'range',
      date: new Date(),
      calendars: 2,
      onChange: function(formated, dates) {
        return inp.trigger('set-date', [dates[0], dates[1]]);
      }
    });
    $('#about-form input[name=name]').change(function() {
      return caption.find('h1').html(this.value);
    });
    return inp.on('set-date', function(e, from, to) {
      var formated;
      formated = inp.DatePickerFormatDate(from, 'b d, Y - ') + inp.DatePickerFormatDate(to, 'b d, Y');
      inp.val(formated);
      caption.find('.date').html(formated);
      caption.addClass('with-date');
      $('#date_from').val(inp.DatePickerFormatDate(from, 'Y-m-d 00:00:00'));
      return $('#date_to').val(inp.DatePickerFormatDate(to, 'Y-m-d 00:00:00'));
    });
  });

}).call(this);
