// Generated by CoffeeScript 1.4.0
(function() {

  jQuery(function($) {
    var inp;
    return inp = $('#report-date').DatePicker({
      format: 'b d, Y',
      mode: 'range',
      date: new Date(),
      calendars: 2,
      onChange: function(formated, dates) {
        inp.val(formated.join(' - '));
        $('#date_from').val(inp.DatePickerFormatDate(dates[0], 'Y-m-d 00:00:00'));
        return $('#date_to').val(inp.DatePickerFormatDate(dates[1], 'Y-m-d 00:00:00'));
      }
    });
  });

}).call(this);
