// Generated by CoffeeScript 1.4.0
(function() {

  jQuery(function($) {
    return $('body').on('click', '#add-widget', function() {
      return showWidgetForm('#types-form');
    });
  });

}).call(this);
