// Generated by CoffeeScript 1.4.0
(function() {

  jQuery(function($) {
    $("#editor").sortable({
      items: "> li.widget"
    });
    $("#editor").disableSelection();
    $('#about-form').showForm();
    window.widgetMap = {
      custom: {
        model: CustomWidget,
        view: CustomView
      },
      image: {
        model: ImageWidget,
        view: ImageView
      },
      list: {
        model: ListWidget,
        view: ListView
      },
      quote: {
        model: QuoteWidget,
        view: QuoteView
      },
      status: {
        model: StatusWidget,
        view: StatusView
      }
    };
    $('*[title]').tipsy({
      gravity: 'n'
    });
    addWidget('custom', {
      data: 'Click',
      name: 'to edit data block'
    });
    return addWidget('custom', {
      data: 'Drag',
      name: 'block to re-arrange'
    });
  });

}).call(this);
