// Generated by CoffeeScript 1.4.0
(function() {

  jQuery(function($) {
    $.fn.showForm = function() {
      $('#forms > .side-block').hide();
      return this.show();
    };
    $.fn.setFormData = function(data) {
      var inp, name, value;
      for (name in data) {
        value = data[name];
        inp = this.find('*[name=' + name + ']');
        if (inp.attr('type') === 'radio') {
          inp.filter(function() {
            return this.value === value;
          }).prop('checked', true).trigger('change');
        } else {
          inp.val(value);
        }
      }
      return this;
    };
    $.fn.getFormData = function() {
      var data;
      data = {};
      this.find(':input').each(function() {
        var name;
        if (this.type === 'radio' && this.checked === false) {
          return null;
        }
        if (this.name.length > 0) {
          if (this.name.indexOf('[]') > 0) {
            name = this.name.replace('[]', '');
            if (name in data) {
              return data[name].push(this.value);
            } else {
              return data[name] = [this.value];
            }
          } else {
            return data[this.name] = this.value;
          }
        }
      });
      return data;
    };
    $.fn.setFormModel = function(model) {
      var form;
      form = this.find('form');
      form = form.length ? form : this;
      form.data('model', model);
      return this;
    };
    $.fn.getFormModel = function() {
      var form;
      form = this.find('form');
      form = form.length ? form : this;
      return form.data('model');
    };
    $.fn.clearForm = function() {
      this.find('input:text, textarea, select').val('');
      return this.setFormModel(null);
    };
    $('#forms form').submit(function() {
      var $this, addBtn, className, coord, data, newAddBtn, view, widget;
      $this = $(this);
      data = $this.getFormData();
      if ($this.getFormModel()) {
        $this.getFormModel().set(data);
      } else {
        className = $this.closest('.side-block').attr('id').replace('-form', '');
        widget = new widgetMap[className].model(data);
        view = new widgetMap[className].view(widget);
        $this.setFormModel(widget);
        addBtn = $('#add-widget');
        coord = addBtn.coords().grid;
        newAddBtn = addBtn.hide().clone();
        Editor.remove_widget(addBtn, function() {
          Editor.add_widget(view.getHtml(), 1, 1, coord.col, coord.row);
          return Editor.add_widget(newAddBtn, 1, 1, coord.col + 1, coord.row);
        });
      }
      return false;
    });
    return $('#forms form .cancel').click(function() {
      return $('#types-form').showForm();
    });
  });

}).call(this);
