// Generated by CoffeeScript 1.4.0
(function() {

  jQuery(function($) {
    var form;
    form = $('#image-form').ajaxForm({
      success: function(data) {
        return form.find('input[name=image]').val(data);
      }
    });
    return form.find(':file').change(function() {
      return form.find('input[name=url]').val(this.value);
    });
  });

}).call(this);
