// Generated by CoffeeScript 1.4.0
(function() {

  jQuery(function($) {
    var form;
    return form = $('#about-form form').submit(function() {
      var data;
      data = form.getFormData();
      data.blocks = [];
      $('#editor > .widget').each(function() {
        return data.blocks.push($(this).data('model').get());
      });
      return false;
    });
  });

}).call(this);
