// Generated by CoffeeScript 1.4.0
(function() {

  jQuery(function($) {
    var form;
    return form = $('#about-form form').submit(function() {
      var data;
      data = form.getFormData();
      data.blocks = [];
      $('#editor > .widget').each(function() {
        return data.blocks.push($(this).data('model').get());
      });
      form.find('button').prop('disabled', true);
      $.ajax({
        url: '/create/',
        data: {
          report: JSON.stringify(data)
        },
        type: 'POST',
        dataType: 'JSON',
        success: function(result) {
          form.find('button').prop('disabled', false);
          if (result.status === 'Success') {
            alert('Your report is created and published');
            return location.href = '/';
          } else {
            return alert(result.content);
          }
        }
      });
      return false;
    });
  });

}).call(this);
