// Generated by CoffeeScript 1.4.0
(function() {

  jQuery(function($) {
    $('#types-form li').click(function() {
      var $this, className;
      $this = $(this);
      className = $this.data('class');
      return $('#' + className + '-form').clearForm().showForm();
    });
    return $('body').on('click', '#types-form li, #editor .widget', function() {
      $('#toggle-tab').removeClass('switch').addClass('close');
      $('#edit-tab').show().addClass('active');
      return $('#about-tab, #add-widget-tab').hide();
    });
  });

}).call(this);
