// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.CustomWidget = (function(_super) {

    __extends(CustomWidget, _super);

    function CustomWidget() {
      return CustomWidget.__super__.constructor.apply(this, arguments);
    }

    CustomWidget.prototype.data = {
      id: 0,
      report_id: 0,
      type: 'custom',
      row: 1,
      col: 1,
      name: '',
      data: '',
      source: ''
    };

    return CustomWidget;

  })(Model);

  jQuery(function($) {
    return window.CustomView = (function(_super) {

      __extends(CustomView, _super);

      function CustomView() {
        return CustomView.__super__.constructor.apply(this, arguments);
      }

      CustomView.prototype.html = $('#custom-tpl').html();

      CustomView.prototype.template = {
        '': {
          on: {
            'click': function() {
              return $('#custom-form').setFormData(this.get()).setFormModel(this).showForm();
            }
          }
        },
        '.block-caption': {
          html: '@data'
        },
        '.area': {
          html: '@name'
        },
        '.tipsy-inner': {
          html: '@source'
        },
        '.widget-hint': {
          cssClass: {
            'empty': {
              '@source': function(text) {
                return $.trim(text).length === 0;
              }
            }
          }
        }
      };

      return CustomView;

    })(View);
  });

}).call(this);
