// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.ListWidget = (function(_super) {

    __extends(ListWidget, _super);

    function ListWidget() {
      return ListWidget.__super__.constructor.apply(this, arguments);
    }

    ListWidget.prototype.data = {
      id: 0,
      report_id: 0,
      order: 0,
      type: 'list',
      name: '',
      list: [],
      list_type: 'bullet',
      source: ''
    };

    return ListWidget;

  })(Model);

  jQuery(function($) {
    return window.ListView = (function(_super) {

      __extends(ListView, _super);

      function ListView() {
        return ListView.__super__.constructor.apply(this, arguments);
      }

      ListView.prototype.html = $('#list-tpl').html();

      ListView.prototype.template = {
        '': {
          on: {
            'click': function() {
              return $('#list-form').setFormModel(this).showForm();
            }
          }
        },
        '.area': {
          html: '@name'
        },
        '.tipsy-inner': {
          html: '@source'
        },
        '.widget-hint': {
          cssClass: {
            'empty': {
              '@source': function(text) {
                return $.trim(text).length === 0;
              }
            }
          }
        },
        'ul': {
          onModel: {
            '@list_type': function(ul, type) {
              return ul.removeClass('square digit').addClass(type);
            }
          },
          each: {
            dataField: 'list',
            template: {
              'span': {
                html: function() {
                  return this.valueOf();
                }
              }
            }
          }
        }
      };

      return ListView;

    })(View);
  });

}).call(this);
