// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.ListWidget = (function(_super) {

    __extends(ListWidget, _super);

    function ListWidget() {
      return ListWidget.__super__.constructor.apply(this, arguments);
    }

    ListWidget.prototype.data = {
      id: 0,
      report_id: 0,
      row: 1,
      col: 1,
      title: '',
      list: ['Direct', 'Direct2'],
      list_type: 'bullet'
    };

    return ListWidget;

  })(Model);

  jQuery(function($) {
    return window.ListView = (function(_super) {

      __extends(ListView, _super);

      function ListView() {
        return ListView.__super__.constructor.apply(this, arguments);
      }

      ListView.prototype.html = $('#list-tpl').html();

      ListView.prototype.template = {
        '': {
          on: {
            'click': function() {
              return $('#list-form').setFormData(this.get()).setFormModel(this).showForm();
            }
          },
          onModel: {
            '@list_type': function(li, type) {
              return li.removeClass('bullet numeric').addClass(type);
            }
          }
        },
        '.area': {
          html: '@title'
        },
        '.square': {
          each: {
            dataField: 'list',
            template: {
              'span': {
                html: function() {
                  return this.valueOf();
                }
              }
            }
          }
        }
      };

      return ListView;

    })(View);
  });

}).call(this);
