// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.QuoteWidget = (function(_super) {

    __extends(QuoteWidget, _super);

    function QuoteWidget() {
      return QuoteWidget.__super__.constructor.apply(this, arguments);
    }

    QuoteWidget.prototype.data = {
      id: 0,
      report_id: 0,
      type: 'quote',
      row: 1,
      col: 1,
      source: '',
      quote: ''
    };

    return QuoteWidget;

  })(Model);

  jQuery(function($) {
    return window.QuoteView = (function(_super) {

      __extends(QuoteView, _super);

      function QuoteView() {
        return QuoteView.__super__.constructor.apply(this, arguments);
      }

      QuoteView.prototype.html = $('#quote-tpl').html();

      QuoteView.prototype.template = {
        '': {
          on: {
            'click': function() {
              return $('#quote-form').setFormData(this.get()).setFormModel(this).showForm();
            }
          }
        },
        'span.text': {
          html: '@quote'
        },
        '.area': {
          html: '@source'
        }
      };

      return QuoteView;

    })(View);
  });

}).call(this);
