// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.StatusWidget = (function(_super) {

    __extends(StatusWidget, _super);

    function StatusWidget() {
      return StatusWidget.__super__.constructor.apply(this, arguments);
    }

    StatusWidget.prototype.data = {
      id: 0,
      report_id: 0,
      row: 1,
      col: 1,
      title: '',
      status: ''
    };

    return StatusWidget;

  })(Model);

  jQuery(function($) {
    return window.StatusView = (function(_super) {

      __extends(StatusView, _super);

      function StatusView() {
        return StatusView.__super__.constructor.apply(this, arguments);
      }

      StatusView.prototype.html = $('#status-tpl').html();

      StatusView.prototype.template = {
        '': {
          on: {
            'click': function() {
              return $('#status-form').setFormData(this.get()).data('model', this).showForm();
            }
          }
        },
        '.block-caption': {
          html: '@title'
        },
        '.area': {
          html: '@status'
        }
      };

      return StatusView;

    })(View);
  });

}).call(this);
