Block:
    type: entity
    table: block
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        reportId:
            type: integer
            unsigned: false
            nullable: false
            column: report_id
        type:
            type: string
            length: 8
            fixed: false
            nullable: false
        position:
            type: integer
            unsigned: false
            nullable: false
    lifecycleCallbacks: {  }
