Report:
    type: entity
    table: report
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        userId:
            type: integer
            unsigned: false
            nullable: false
            column: user_id
        name:
            type: string
            length: 128
            fixed: false
            nullable: false
        dateFrom:
            type: datetime
            nullable: false
            column: date_from
        dateTo:
            type: datetime
            nullable: false
            column: date_to
    lifecycleCallbacks: {  }
